{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.BottomNavigation",
    "module": "release",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "release-1.1.1.aar",
          "url": "release-1.1.1.aar",
          "size": 25408,
          "sha512": "095f50ed416a048729b3bdad8e9e6fb95f6736fece496c76f409e908b7cd937910e49698cf848ee288c189ad847bf761ebda52ed4284e11cbb8ee03afbe0ef30",
          "sha256": "cec26ba96fede4ce96610a0fc7b9dcdb3c6f005bb46946142da4cfdf6f210c13",
          "sha1": "6baff04e1ee6027caf1ac912ef1d46e0193bbaaf",
          "md5": "7388cb15246d2cbdfdb2d5231c147ac6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "release-1.1.1.aar",
          "url": "release-1.1.1.aar",
          "size": 25408,
          "sha512": "095f50ed416a048729b3bdad8e9e6fb95f6736fece496c76f409e908b7cd937910e49698cf848ee288c189ad847bf761ebda52ed4284e11cbb8ee03afbe0ef30",
          "sha256": "cec26ba96fede4ce96610a0fc7b9dcdb3c6f005bb46946142da4cfdf6f210c13",
          "sha1": "6baff04e1ee6027caf1ac912ef1d46e0193bbaaf",
          "md5": "7388cb15246d2cbdfdb2d5231c147ac6"
        }
      ]
    }
  ]
}
